version: '3.6'

services:
   
   
    redis:
      image: 'bitnami/redis:latest'
      ports:
        - 6379:6379
      networks:
        - n1
      environment:
          - ALLOW_EMPTY_PASSWORD=yes

networks:
  n1:
    external: true